# Generated by Django 3.1.5 on 2022-04-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICAEstaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('variable', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SerieTiempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('variable', models.CharField(max_length=255)),
            ],
            options={
                'db_table': None,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetadataEstacionesAire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('parametro_instrumentacion_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('limite_norma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VariablesDisponibles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=255)),
            ],
        ),
    ]
